publish:
  docker:
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    registry: registry.chmuul.net
    insecure: true
    username: $$REGISTRY_USERNAME
    password: $$REGISTRY_PASSWORD
    auth: $$REGISTRY_AUTH
    file: Dockerfile.ubuntu-16.04
    repo: ansible-controller
    tag:
      - ubuntu-16.04
      - ubuntu

branches:
  - master
