publish:
  docker:
    registry: $$REGISTRY_HOST
    username: $$REGISTRY_USERNAME
    password: $$REGISTRY_PASSWORD
    email: $$REGISTRY_EMAIL
    file: Dockerfile.$$OS
    load: build/ansible-$$OS.tar
    save:
      destination: build/ansible-$$OS.tar
      tag: $$OS
    repo: ansible
    tag:
      - $$OS

matrix:
  OS:
  - alpine-3
  - debian-8
  - ubuntu-16.04
  - fedora-24

branches:
  - master
