publish:
  docker:
    registry: registry.chmuul.net
    insecure: true
    username: $$REGISTRY_USERNAME
    password: $$REGISTRY_PASSWORD
    email:
    file: Dockerfile.ubuntu-16.04
    repo: ansible-controller
    tag:
      - ubuntu-16.04
      - ubuntu

branches:
  - master
