publish:
  docker:
    registry: registry.chmuul.net
    insecure: true
    username: $$REGISTRY_USERNAME
    password: $$REGISTRY_PASSWORD
    email: $$REGISTRY_EMAIL
    file: Dockerfile.$$OS
    repo: ansible-controller
    tag:
      - $$OS

matrix:
  OS:
  - ubuntu-16.04
  - fedora-24

branches:
  - master
