publish:
  docker:
    registry: registry.chmuul.net:443
    insecure: true
    username: $$REGISTRY_USERNAME
    password: $$REGISTRY_PASSWORD
    email: $$REGISTRY_EMAIL
    file: Dockerfile.ubuntu-16.04
    repo: registry.chmuul.net/ansible-controller
    tag:
      - ubuntu-16.04
      - ubuntu

branches:
  - master
