pipeline:
  build-ubuntu-16:
    group: build
    image: plugins/docker
    repo: lerentis/ansible
    tag: ubuntu-16.04
    dockerfile: ubuntu-16.04/Dockerfile
    dry_run: true
    when:
      event: [ push, pull_request ]

  build-ubuntu-14:
    group: build
    image: plugins/docker
    repo: lerentis/ansible
    tag: ubuntu-14.04
    dockerfile: ubuntu-14.04/Dockerfile
    dry_run: true
    when:
      event: [ push, pull_request ]

  build-fedora-24:
    group: build
    image: plugins/docker
    repo: lerentis/ansible
    tag: fedora-24
    dockerfile: fedora-24/Dockerfile
    dry_run: true
    when:
      event: [ push, pull_request ]

  build-alpine-3:
    group: build
    image: plugins/docker
    repo: lerentis/ansible
    tag: alpine-3
    dockerfile: alpine-3/Dockerfile
    dry_run: true
    when:
      event: [ push, pull_request ]

  build-debian-8:
    group: build
    image: plugins/docker
    repo: lerentis/ansible
    tag: debian-8
    dockerfile: debian-8/Dockerfile
    dry_run: true
    when:
      event: [ push, pull_request ]

  build-debian-7:
    group: build
    image: plugins/docker
    repo: lerentis/ansible
    tag: debian-7
    dockerfile: debian-8/Dockerfile
    dry_run: true
    when:
      event: [ push, pull_request ]

  build-centos-7:
    group: build
    image: plugins/docker
    repo: lerentis/ansible
    tag: centos-7
    dockerfile: centos-7/Dockerfile
    dry_run: true
    when:
      event: [ push, pull_request ]

  build-arch:
    group: build
    image: plugins/docker
    repo: lerentis/ansible
    tag: arch
    dockerfile: arch/Dockerfile
    dry_run: true
    when:
      event: [ push, pull_request ]

  build-ubuntu-16-publish:
    group: build
    image: plugins/docker
    repo: lerentis/ansible
    tag: ubuntu-16.04
    dockerfile: ubuntu-16.04/Dockerfile
    secrets: [ docker_username, docker_password ]
    when:
      event: [ tag ]

  build-ubuntu-14-publish:
    group: build
    image: plugins/docker
    repo: lerentis/ansible
    tag: ubuntu-14.04
    dockerfile: ubuntu-14.04/Dockerfile
    secrets: [ docker_username, docker_password ]
    when:
      event: [ tag ]

  build-fedora-24-publish:
    group: build
    image: plugins/docker
    repo: lerentis/ansible
    tag: fedora-24
    dockerfile: fedora-24/Dockerfile
    secrets: [ docker_username, docker_password ]
    when:
      event: [ tag ]

  build-alpine-3-publish:
    group: build
    image: plugins/docker
    repo: lerentis/ansible
    tag: alpine-3
    dockerfile: alpine-3/Dockerfile
    secrets: [ docker_username, docker_password ]
    when:
      event: [ tag ]

  build-debian-8-publish:
    group: build
    image: plugins/docker
    repo: lerentis/ansible
    tag: debian-8
    dockerfile: debian-8/Dockerfile
    secrets: [ docker_username, docker_password ]
    when:
      event: [ tag ]

  build-debian-7-publish:
    group: build
    image: plugins/docker
    repo: lerentis/ansible
    tag: debian-7
    dockerfile: debian-8/Dockerfile
    secrets: [ docker_username, docker_password ]
    when:
      event: [ tag ]

  build-centos-7-publish:
    group: build
    image: plugins/docker
    repo: lerentis/ansible
    tag: centos-7
    dockerfile: centos-7/Dockerfile
    secrets: [ docker_username, docker_password ]
    when:
      event: [ tag ]

  build-arch-publish:
    group: build
    image: plugins/docker
    repo: lerentis/ansible
    tag: arch
    dockerfile: arch/Dockerfile
    secrets: [ docker_username, docker_password ]
    when:
      event: [ tag ]

telegram:
    image: appleboy/drone-telegram
    token: 335668211:AAF-YgId7iI6ANBuZVy4uVOYYqA4R4uAaqY
    to: 14852963
    message: Commit {{ commit.link }} ran with build {{ build.number }} and finished with status {{ build.status }}.
    when:
      status:  [ failure, success ]
