publish:
  docker:
    username: $$REGISTRY_USERNAME
    password: $$REGISTRY_PASSWORD
    email: $$REGISTRY_EMAIL
    #file: Dockerfile.$$OS
    context: $$OS
    repo: chmuul/ansible
    tag:
      - $$OS

matrix:
  OS:
  - alpine-3
  - debian-8
  - ubuntu-16.04
  - fedora-24

branches:
  - master
