publish:
  docker:
    registry: $$REGISTRY_HOST
    username: $$REGISTRY_USERNAME
    password: $$REGISTRY_PASSWORD
    email: $$REGISTRY_EMAIL
    file: Dockerfile.$$OS
    repo: ansible-controller
    tag:
      - $$OS

matrix:
  OS:
  - debian-8
  - ubuntu-16.04
  - fedora-24

branches:
  - master
