publish:
  docker:
    username: $$REGISTRY_USERNAME
    password: $$REGISTRY_PASSWORD
    email: $$REGISTRY_EMAIL
    file: Dockerfile.$$OS
    load: image.tar
    save:
      destination: image.tar
      tag: $$OS
    repo: chmuul/ansible
    tag:
      - $$OS

matrix:
  OS:
  - alpine-3
  - debian-8
  - ubuntu-16.04
  - fedora-24

cache:
  mount:
    - image.tar
    - .git

branches:
  - master
