---
kind: pipeline
name: ansible-containers

platform:
  os: linux
  arch: amd64

concurrency:
  limit: 9

steps:

- name: build-ubuntu-19
  image: plugins/docker
  settings:
    dockerfile: ubuntu-19.04/Dockerfile
    dry_run: true
    repo: lerentis/ansible
    tag: ubuntu-19.04
  when:
    event:
    - push
    - pull_request

- name: build-ubuntu-18
  image: plugins/docker
  settings:
    dockerfile: ubuntu-18.04/Dockerfile
    dry_run: true
    repo: lerentis/ansible
    tag: ubuntu-18.04
  when:
    event:
    - push
    - pull_request

- name: build-ubuntu-16
  image: plugins/docker
  settings:
    dockerfile: ubuntu-16.04/Dockerfile
    dry_run: true
    repo: lerentis/ansible
    tag: ubuntu-16.04
  when:
    event:
    - push
    - pull_request

- name: build-ubuntu-14
  image: plugins/docker
  settings:
    dockerfile: ubuntu-14.04/Dockerfile
    dry_run: true
    repo: lerentis/ansible
    tag: ubuntu-14.04
  when:
    event:
    - push
    - pull_request

- name: build-fedora-24
  image: plugins/docker
  settings:
    dockerfile: fedora-24/Dockerfile
    dry_run: true
    repo: lerentis/ansible
    tag: fedora-24
  when:
    event:
    - push
    - pull_request

- name: build-alpine-3
  image: plugins/docker
  settings:
    dockerfile: alpine-3/Dockerfile
    dry_run: true
    repo: lerentis/ansible
    tag: alpine-3
  when:
    event:
    - push
    - pull_request

- name: build-debian-8
  image: plugins/docker
  settings:
    dockerfile: debian-8/Dockerfile
    dry_run: true
    repo: lerentis/ansible
    tag: debian-8
  when:
    event:
    - push
    - pull_request

- name: build-debian-7
  image: plugins/docker
  settings:
    dockerfile: debian-8/Dockerfile
    dry_run: true
    repo: lerentis/ansible
    tag: debian-7
  when:
    event:
    - push
    - pull_request

- name: build-centos-7
  image: plugins/docker
  settings:
    dockerfile: centos-7/Dockerfile
    dry_run: true
    repo: lerentis/ansible
    tag: centos-7
  when:
    event:
    - push
    - pull_request

- name: build-arch
  image: plugins/docker
  settings:
    dockerfile: arch/Dockerfile
    dry_run: true
    repo: lerentis/ansible
    tag: arch
  when:
    event:
    - push
    - pull_request

- name: build-ubuntu-18-publish
  image: plugins/docker
  settings:
    dockerfile: ubuntu-18.04/Dockerfile
    password:
      from_secret: docker_password
    repo: lerentis/ansible
    tag: ubuntu-18.04
    username:
      from_secret: docker_username
  when:
    event:
    - tag

- name: build-ubuntu-19-publish
  image: plugins/docker
  settings:
    dockerfile: ubuntu-19.04/Dockerfile
    password:
      from_secret: docker_password
    repo: lerentis/ansible
    tag: ubuntu-19.04
    username:
      from_secret: docker_username
  when:
    event:
    - tag

- name: build-ubuntu-16-publish
  image: plugins/docker
  settings:
    dockerfile: ubuntu-16.04/Dockerfile
    password:
      from_secret: docker_password
    repo: lerentis/ansible
    tag: ubuntu-16.04
    username:
      from_secret: docker_username
  when:
    event:
    - tag

- name: build-ubuntu-14-publish
  image: plugins/docker
  settings:
    dockerfile: ubuntu-14.04/Dockerfile
    password:
      from_secret: docker_password
    repo: lerentis/ansible
    tag: ubuntu-14.04
    username:
      from_secret: docker_username
  when:
    event:
    - tag

- name: build-fedora-24-publish
  image: plugins/docker
  settings:
    dockerfile: fedora-24/Dockerfile
    password:
      from_secret: docker_password
    repo: lerentis/ansible
    tag: fedora-24
    username:
      from_secret: docker_username
  when:
    event:
    - tag

- name: build-alpine-3-publish
  image: plugins/docker
  settings:
    dockerfile: alpine-3/Dockerfile
    password:
      from_secret: docker_password
    repo: lerentis/ansible
    tag: alpine-3
    username:
      from_secret: docker_username
  when:
    event:
    - tag

- name: build-debian-8-publish
  image: plugins/docker
  settings:
    dockerfile: debian-8/Dockerfile
    password:
      from_secret: docker_password
    repo: lerentis/ansible
    tag: debian-8
    username:
      from_secret: docker_username
  when:
    event:
    - tag

- name: build-debian-7-publish
  image: plugins/docker
  settings:
    dockerfile: debian-8/Dockerfile
    password:
      from_secret: docker_password
    repo: lerentis/ansible
    tag: debian-7
    username:
      from_secret: docker_username
  when:
    event:
    - tag

- name: build-centos-7-publish
  image: plugins/docker
  settings:
    dockerfile: centos-7/Dockerfile
    password:
      from_secret: docker_password
    repo: lerentis/ansible
    tag: centos-7
    username:
      from_secret: docker_username
  when:
    event:
    - tag

- name: build-arch-publish
  image: plugins/docker
  settings:
    dockerfile: arch/Dockerfile
    password:
      from_secret: docker_password
    repo: lerentis/ansible
    tag: arch
    username:
      from_secret: docker_username
  when:
    event:
    - tag

- name: notify
  image: appleboy/drone-telegram
  settings:
    message: "Commit {{ commit.link }} ran with build {{ build.number }} and finished with status {{ build.status }}."
    to: 14852963
    token: 335668211:AAF-YgId7iI6ANBuZVy4uVOYYqA4R4uAaqY
  when:
    status:
    - failure
    - success
  depends_on:
  - build-ubuntu-19
  - build-ubuntu-18
  - build-ubuntu-16
  - build-ubuntu-14
  - build-fedora-24
  - build-alpine-3
  - build-debian-8
  - build-debian-7
  - build-centos-7
  - build-arch
  - build-ubuntu-19-publish
  - build-ubuntu-18-publish
  - build-ubuntu-16-publish
  - build-ubuntu-14-publish
  - build-fedora-24-publish
  - build-alpine-3-publish
  - build-debian-8-publish
  - build-debian-7-publish
  - build-centos-7-publish
  - build-arch-publish
