FROM debian:8

RUN apt-get update \
    && apt-get install -yq --no-install-recommends \
      build-essential \
      libffi-dev \
      libssl-dev \
      python \
      python-dev \
      python-pip \
    && apt-get autoclean \
    && pip install --upgrade ansible

WORKDIR /site

CMD ["ansible-playbook", "--help"]
